version = 3
final_space = true

[secondary_prompt]
  template = '  > '
  foreground = 'default'
  background = 'transparent'

[transient_prompt]
  # template = '{{ if gt .Code 0 }} {{ else }}󰘳 {{ end }}{{ .Segments.DirP.Path }}  '
  foreground = 'default'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' {{ if eq .Env.POSH_VI_MODE "NORMAL" }}  NORM {{ else }} 󰏪 INS {{ end }} '
    foreground = 'cyan'
    background = 'transparent'
    type = 'text'
    style = 'powerline'

  [[blocks.segments]]
    template = ' 󰔟 {{ .FormattedMs }}'
    foreground = 'lightYellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      min = 500.0

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    alias = 'DirP'
    template = ' {{ .Path }} '
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '  '
      folder_separator_icon = '/'
      hide_root_location = false
      home_icon = ' '
      max_depth = 3.0
      style = 'agnoster_short'

      [blocks.segments.properties.mapped_locations]
        '/data/data/com.termux' = ' '
        '/data/data/com.termux/files' = ' '
        '/data/data/com.termux/files/usr' = ' '
        '/data/data/com.termux/files/usr/bin' = ' '
        '/storage/emulated/0/Documents/personal' = '󰠮b'
        '~' = ' '
        '~/dev' = ' '
        '~/dotfiles' = ' '
        '~/storage/shared/Documents/personal' = '󰠮b'
        '~/storage/shared/Download/' = ' '
        '~/storage/shared/indev/' = '󰘦 '

  [[blocks.segments]]
    template = '  {{ .HEAD }}{{ if .Working.Changed }} {{ end }}{{ if .Staging.Changed }} {{ end }}{{ if .StashCount }} {{ .StashCount }}{{ end }}{{ if gt .Behind 0 }} ⇣{{ .Behind }}{{ end }}{{ if gt .Ahead 0 }} ⇡{{ .Ahead }}{{ end }} '
    foreground = 'green'
    background = 'transparent'
    type = 'git'
    style = 'powerline'

    [blocks.segments.properties]
      branch_max_length = 28.0
      cache_duration = 'none'
      display_status_detail = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  {{ .Venv }} '
    foreground = 'lightGreen'
    background = 'transparent'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ if gt .Code 0 }}  {{ .Code }}{{ end }}'
    foreground = 'default'
    background = 'transparent'
    type = 'status'
    style = 'powerline'

    [blocks.segments.properties]
      always_enabled = false
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' '
    foreground = 'magenta'
    background = 'transparent'
    type = 'text'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
